# Generated by Django 3.1.7 on 2021-04-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210406_2042'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_article',
            field=models.ManyToManyField(to='articles.Article'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
