# Generated by Django 3.1.7 on 2021-04-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20210418_1145'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='keyword',
            table=None,
        ),
    ]
