# Generated by Django 3.2 on 2021-04-27 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20210418_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='tag_name',
            new_name='name',
        ),
    ]
