# Generated by Django 3.1.7 on 2021-04-18 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20210418_1145'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AddField(
            model_name='comment',
            name='is_moderate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.CharField(max_length=60, verbose_name='Имя комментатора'),
        ),
        migrations.CreateModel(
            name='Article_Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.keyword')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.ManyToManyField(through='articles.Article_Keyword', to='tags.Keyword'),
        ),
    ]
