# Generated by Django 3.1.7 on 2021-04-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20210413_1752'),
        ('articles', '0002_auto_20210406_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.ManyToManyField(to='tags.Keyword'),
        ),
    ]
