# Generated by Django 3.1.7 on 2021-04-15 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20210413_1752'),
        ('articles', '0003_article_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('tag_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.keyword')),
            ],
        ),
    ]
