# Generated by Django 3.1.7 on 2021-04-21 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20210418_1156'),
        ('articles', '0006_article_article_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article_keyword',
            unique_together={('article', 'tag')},
        ),
    ]
