# Generated by Django 3.2 on 2021-04-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20210418_1156'),
        ('articles', '0007_auto_20210421_2029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article_Keyword',
            new_name='ArticleKeyword',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_title',
            new_name='title',
        ),
    ]
